# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: basket-investing
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ganesh31ram@gmail.com
    password: bhsm mufl efwf iwbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
